<?php
require_once __DIR__ . '/includes/bootstrap.php';
$pageTitle = 'Termos de uso';
require __DIR__ . '/includes/header.php';
?>
<div class="mx-auto max-w-3xl px-4 py-12 sm:px-6 lg:px-8">
  <h1 class="mb-8 text-3xl font-bold">Termos de uso</h1>
  <div class="space-y-4 text-sm leading-relaxed">
    <p>O presente termo regula, de forma detalhada, as condições gerais de utilização do website "Habitou Imóveis" (www.habitou.com.br), plataforma de tecnologia e publicidade online destinada a aproximar pessoas em busca de imóveis (Usuários) de corretores, imobiliárias e proprietários (Anunciantes), para divulgação de imóveis à venda ou para locação em todo o Brasil.</p>

    <h2 class="pt-4 text-lg font-bold">Definições</h2>
    <p>Para os fins destes Termos de Uso, as seguintes definições serão adotadas:</p>
    <p><strong>Termos de uso:</strong> são os termos contidos nesta página.</p>
    <p><strong>Habitou Imóveis, portal ou plataforma:</strong> website com endereço www.habitou.com.br e os subdomínios, aplicativos ou sistemas a ele associados.</p>
    <p><strong>Anunciante:</strong> corretor de imóveis autônomo, imobiliária (devidamente registrados no CRECI de seu estado) ou proprietário particular que, sem intermediação de corretor, publica anúncio de imóvel de sua titularidade no portal.</p>
    <p><strong>Usuário ou Cliente:</strong> qualquer pessoa que acessa, navega ou utiliza o Habitou Imóveis, inclusive para buscar imóveis, favoritar anúncios ou entrar em contato com um Anunciante.</p>
    <p><strong>Você:</strong> é o Usuário ou o Anunciante, dependendo do contexto em que esta definição é utilizada — toda pessoa que usa a plataforma é, ao mesmo tempo, Usuária destes Termos.</p>

    <h2 class="pt-4 text-lg font-bold">Leitura e Aceitação</h2>
    <p>Antes de acessar ou utilizar qualquer parte do Habitou Imóveis, VOCÊ deverá ler com atenção estes Termos. O uso do Habitou Imóveis, ou acesso a este — inclusive o cadastro de conta, o envio de mensagem de interesse em um imóvel ou o uso do formulário "Fale conosco" — implicará que VOCÊ leu, entendeu e aceitou cumprir integralmente com os termos, condições e advertências aqui estabelecidos, em especial os artigos que tratam da natureza do serviço, da comunicação via WhatsApp e da ausência de responsabilidade do portal pela negociação entre as partes. Caso VOCÊ não concorde com qualquer disposição destes Termos, não deverá utilizar a plataforma.</p>

    <h2 class="pt-4 text-lg font-bold">1. Como Funciona o Habitou Imóveis</h2>
    <p>O Habitou Imóveis é um portal de buscas e anúncios de imóveis. Em linhas gerais, o negócio funciona assim:</p>
    <p>(a) <strong>Busca:</strong> qualquer visitante pode buscar imóveis à venda ou para locação por cidade, tipo, faixa de preço e demais características, sem necessidade de cadastro;</p>
    <p>(b) <strong>Cadastro de conta:</strong> para favoritar imóveis, publicar anúncios ou gerenciar um perfil de corretor/imobiliária, é necessário criar uma conta, nos termos do Artigo 2 abaixo;</p>
    <p>(c) <strong>Anúncios:</strong> Anunciantes publicam seus imóveis manualmente pelo painel (com fotos, descrição, localização no mapa e características) ou, no caso de imobiliárias com carteira grande, por importação automática de um arquivo XML no padrão do mercado (o que chamamos internamente de VRSync) — em ambos os casos, o conteúdo do anúncio é de responsabilidade exclusiva de quem o publicou ou de quem gerou o arquivo importado, conforme o Artigo 5;</p>
    <p>(d) <strong>Planos pagos:</strong> Anunciantes que queiram publicar mais de um número limitado de imóveis simultaneamente contratam um plano de assinatura paga, detalhado nos <a href="<?= base_url('termos-assinatura.php') ?>" class="text-brand-primary hover:underline">Termos do contrato de assinatura</a>;</p>
    <p>(e) <strong>Contato:</strong> ao encontrar um imóvel de interesse, o Usuário entra em contato diretamente com o Anunciante — hoje, principalmente pelo botão "Conversar no WhatsApp" ou pelo formulário de mensagem do próprio anúncio, que redireciona o Usuário para uma conversa de WhatsApp com o número informado pelo Anunciante, conforme detalhado no Artigo 7;</p>
    <p>(f) <strong>Favoritos e recomendações:</strong> Usuários logados podem favoritar imóveis e recebem sugestões de imóveis potencialmente do interesse deles com base na localização informada ou autorizada pelo navegador e no histórico de imóveis visualizados, conforme detalhado na nossa <a href="<?= base_url('politica-de-privacidade.php') ?>" class="text-brand-primary hover:underline">Política de privacidade</a>;</p>
    <p>(g) <strong>Perfis públicos:</strong> imobiliárias e corretores possuem uma página pública própria no portal, reunindo seus anúncios ativos e dados de contato.</p>
    <p>Em nenhuma dessas etapas o Habitou Imóveis participa da negociação em si, da visita ao imóvel, da assinatura de contratos ou de qualquer pagamento entre as partes — essa distinção é o núcleo destes Termos e está detalhada no Artigo 4.</p>

    <h2 class="pt-4 text-lg font-bold">2. Cadastro e Tipos de Conta</h2>
    <p><strong>2.1.</strong> Ao se cadastrar, VOCÊ escolhe um entre três tipos de conta: (i) <em>Comprador/anunciante particular</em> — para buscar imóveis, favoritar anúncios e, se quiser, anunciar um imóvel de sua propriedade sem intermediação de corretor; (ii) <em>Corretor autônomo</em> — exige informar um número de CRECI; ou (iii) <em>Imobiliária</em> — exige nome e CNPJ da empresa, e cria um perfil de imobiliária que fica em análise até aprovação do administrador do portal.</p>
    <p><strong>2.2.</strong> O CRECI informado por corretores e o CNPJ informado por imobiliárias são <strong>autodeclarados</strong> no momento do cadastro. O Habitou Imóveis pode, mas não se obriga a, verificar essas informações junto aos órgãos competentes antes de liberar a publicação de anúncios — a responsabilidade pela veracidade desses dados é sempre do Anunciante, nos termos do Artigo 5.</p>
    <p><strong>2.3.</strong> VOCÊ é responsável por manter a confidencialidade da senha da sua conta e por todas as atividades realizadas nela. Comunique imediatamente qualquer uso não autorizado através da nossa <a href="<?= base_url('fale-conosco.php') ?>" class="text-brand-primary hover:underline">página de contato</a>.</p>

    <h2 class="pt-4 text-lg font-bold">3. Natureza do Serviço</h2>
    <p>O Habitou Imóveis é um provedor de hospedagem de anúncios e plataforma de tecnologia e publicidade online. Nosso serviço consiste exclusivamente em aproximar Usuários (buscando imóveis) e Anunciantes (corretores, imobiliárias e proprietários). O Habitou Imóveis <strong>não é uma imobiliária</strong>, <strong>não atua como corretor de imóveis</strong> e <strong>não recebe comissão</strong> sobre vendas ou locações realizadas a partir dos anúncios publicados na plataforma. A receita do Habitou Imóveis vem exclusivamente da assinatura paga dos planos de anúncio pelos Anunciantes.</p>

    <h2 class="pt-4 text-lg font-bold">4. Ausência de Intermediação e Responsabilidade</h2>
    <p><strong>4.1.</strong> O Habitou Imóveis NÃO participa, NÃO interfere e NÃO se responsabiliza por qualquer etapa da negociação entre o Usuário e o Anunciante, entre corretores, imobiliárias e proprietários, ou entre quaisquer outras partes envolvidas em uma transação imobiliária originada a partir de um anúncio publicado na plataforma.</p>
    <p><strong>4.2.</strong> Toda a comunicação (inclusive a que ocorre via WhatsApp após ser iniciada pelo portal, nos termos do Artigo 7), o agendamento de visitas, a verificação de documentação, a assinatura de contratos e as transferências financeiras (pagamento de sinal, aluguel, condomínio, comissão ou compra) ocorrem estritamente fora do ambiente da plataforma, sob inteira responsabilidade das partes envolvidas.</p>
    <p><strong>4.3.</strong> O Habitou Imóveis é isento de qualquer responsabilidade civil, criminal, fiscal ou trabalhista decorrente de fraudes, inadimplência, propaganda enganosa, vícios ocultos nos imóveis anunciados, descumprimento contratual, divergência entre o anunciado e a realidade do imóvel, ou qualquer dano moral e/ou material sofrido por qualquer uma das partes durante ou após a negociação — inclusive quando o anúncio foi publicado por importação automática de arquivo XML fornecido pelo próprio Anunciante, sem revisão manual do portal.</p>
    <p><strong>4.4.</strong> Ao aceitar estes Termos, VOCÊ reconhece expressamente que o Habitou Imóveis atua apenas como vitrine digital e canal de aproximação, e que qualquer decisão de negociar, visitar, contratar ou pagar por um imóvel anunciado é de sua exclusiva e integral responsabilidade.</p>

    <h2 class="pt-4 text-lg font-bold">5. Obrigações do Anunciante (Corretor, Imobiliária ou Proprietário)</h2>
    <p><strong>5.1.</strong> O Anunciante que se cadastra como corretor ou imobiliária declara possuir registro ativo e regular no Conselho Regional de Corretores de Imóveis (CRECI) de seu estado para exercer a profissão, ou, no caso de imobiliárias, possuir CNPJ regular e corretor(es) responsável(is) devidamente registrado(s). O Anunciante que se cadastra como proprietário particular declara ser o legítimo proprietário do imóvel anunciado ou possuir autorização expressa do proprietário para anunciá-lo.</p>
    <p><strong>5.2.</strong> O Anunciante é o único e exclusivo responsável pela veracidade, clareza e legalidade das informações, fotos, documentos e preços publicados em seus anúncios — inclusive os importados automaticamente via arquivo XML — assumindo toda a responsabilidade perante o Código de Defesa do Consumidor e demais legislações aplicáveis, inclusive quanto à titularidade do imóvel anunciado e à autorização do proprietário para publicá-lo.</p>
    <p><strong>5.3.</strong> O Anunciante é responsável por manter seus anúncios atualizados, removendo ou pausando anúncios de imóveis que já tenham sido vendidos, alugados ou retirados do mercado.</p>
    <p><strong>5.4.</strong> O Habitou Imóveis reserva-se o direito de excluir anúncios, suspender ou banir Anunciantes que apresentem comportamento suspeito, denúncias de fraude, informações falsas ou inadimplência com a assinatura do plano contratado junto ao portal, sem necessidade de aviso prévio ou reembolso dos valores já pagos.</p>

    <h2 class="pt-4 text-lg font-bold">6. Obrigações do Usuário (Cliente Final)</h2>
    <p><strong>6.1.</strong> É responsabilidade exclusiva do Usuário certificar-se da idoneidade do Anunciante, exigir a apresentação do registro no CRECI (quando aplicável), e conferir a matrícula e a situação legal do imóvel junto ao Cartório de Registro de Imóveis competente antes de realizar qualquer pagamento, assinatura de contrato ou compromisso.</p>
    <p><strong>6.2.</strong> O Usuário compreende e concorda que o Habitou Imóveis jamais solicitará depósitos, chaves PIX ou transferências bancárias para reserva, sinal ou pagamento de imóveis — qualquer solicitação nesse sentido feita em nome do portal deve ser considerada fraudulenta e denunciada imediatamente através da nossa <a href="<?= base_url('fale-conosco.php') ?>" class="text-brand-primary hover:underline">página de contato</a>.</p>

    <h2 class="pt-4 text-lg font-bold">7. Comunicação via WhatsApp</h2>
    <p><strong>7.1.</strong> Ao clicar em "Conversar no WhatsApp", "Enviar mensagem" na página de um imóvel, ou ao enviar o formulário da página "Fale conosco", VOCÊ é redirecionado para uma conversa de WhatsApp — com o Anunciante responsável pelo imóvel (imobiliária, corretor ou proprietário), no caso do formulário do anúncio, ou com o próprio Habitou Imóveis, no caso do "Fale conosco" — já com uma mensagem pré-preenchida contendo os dados que VOCÊ digitou no formulário (nome, e-mail, telefone e, quando aplicável, assunto e mensagem).</p>
    <p><strong>7.2.</strong> Essa conversa passa a ocorrer inteiramente dentro do WhatsApp, fora do ambiente do Habitou Imóveis, e está sujeita aos Termos de Serviço e à Política de Privacidade do próprio WhatsApp (Meta Platforms, Inc.), sobre os quais o Habitou Imóveis não tem controle nem responsabilidade.</p>
    <p><strong>7.3.</strong> O conteúdo, tom, frequência e qualquer desdobramento comercial dessa conversa são de responsabilidade exclusiva das partes que a conduzem — o Habitou Imóveis apenas gera o link inicial de contato e não acompanha, armazena de forma centralizada, nem modera as mensagens trocadas no WhatsApp.</p>

    <h2 class="pt-4 text-lg font-bold">8. Planos, Pagamento e Importação de Anúncios</h2>
    <p><strong>8.1.</strong> Anunciantes que desejam publicar mais imóveis simultaneamente do que o limite gratuito contratam um dos planos pagos disponíveis na página de <a href="<?= base_url('planos.php') ?>" class="text-brand-primary hover:underline">Planos</a>, regidos pelos <a href="<?= base_url('termos-assinatura.php') ?>" class="text-brand-primary hover:underline">Termos do contrato de assinatura</a>, que tratam de cobrança, cancelamento e suspensão por inadimplência.</p>
    <p><strong>8.2.</strong> Imobiliárias com carteira de imóveis grande podem, alternativamente a cadastrar cada imóvel manualmente, importar seus anúncios em lote através de um arquivo XML no formato compatível com o sistema (recurso identificado internamente como VRSync). Nesse caso, o conteúdo de cada anúncio importado é gerado automaticamente a partir do arquivo fornecido pela própria imobiliária ou por seu fornecedor de tecnologia, sem revisão manual individual pelo Habitou Imóveis — a responsabilidade pela exatidão desse conteúdo permanece integralmente com a imobiliária, nos termos do Artigo 5.</p>

    <h2 class="pt-4 text-lg font-bold">9. Limitações e Uso Adequado</h2>
    <p>O acesso e a utilização do Habitou Imóveis são oferecidos a VOCÊ unicamente para o seu uso pessoal e, no caso de Anunciantes, profissional na divulgação de imóveis. Entre outros fatores, VOCÊ concorda que não poderá: modificar, copiar, distribuir, transmitir, exibir, reproduzir, publicar, licenciar, criar trabalhos derivados, ou vender qualquer informação, software ou banco de dados obtidos pelo Habitou Imóveis; enviar informações falsas, enganosas, ofensivas ou que violem a lei; efetuar cadastro utilizando informações falsas ou de terceiros; transmitir códigos maliciosos ou vírus; tentar acessar áreas restritas sem autorização; utilizar rotinas automatizadas (scraping/raspagem de dados) para coletar em massa o conteúdo do portal; ou realizar qualquer atividade que viole direitos de propriedade intelectual de terceiros.</p>

    <h2 class="pt-4 text-lg font-bold">10. Conteúdo do Portal e Conteúdo Publicado por Você</h2>
    <p>Todo o layout, marca, logotipo, textos institucionais e o código-fonte do Habitou Imóveis são de propriedade do portal e protegidos por direitos autorais, não podendo ser reproduzidos sem autorização prévia. Já os anúncios, fotos, descrições e demais conteúdos publicados por Anunciantes (manualmente ou por importação de XML) permanecem sob responsabilidade de quem os publicou — ao publicar um anúncio, o Anunciante garante possuir os direitos sobre as fotos e textos utilizados e concede ao Habitou Imóveis licença não exclusiva, gratuita e revogável para exibi-los na plataforma (inclusive em materiais de divulgação do próprio portal) enquanto o anúncio estiver ativo.</p>

    <h2 class="pt-4 text-lg font-bold">11. Links Eletrônicos e Referências a Terceiros</h2>
    <p>O Habitou Imóveis pode conter links para sites e serviços de terceiros — WhatsApp, redes sociais de Anunciantes, o Mercado Pago (processador de pagamento dos planos), OpenStreetMap/CARTO (mapas) e outros. Esses links e integrações são fornecidos apenas por conveniência ou necessidade operacional, e o portal não se responsabiliza pelo conteúdo, disponibilidade, práticas de privacidade ou qualquer dano decorrente do uso desses serviços externos.</p>

    <h2 class="pt-4 text-lg font-bold">12. Suspensão e Encerramento de Conta</h2>
    <p>O Habitou Imóveis pode suspender ou encerrar, a qualquer momento e sem aviso prévio, o acesso de qualquer Usuário ou Anunciante que viole estes Termos de Uso, pratique atividade fraudulenta, ou cujo comportamento coloque em risco outros usuários da plataforma ou a integridade do serviço. VOCÊ também pode encerrar sua própria conta a qualquer momento, solicitando a exclusão pela nossa <a href="<?= base_url('fale-conosco.php') ?>" class="text-brand-primary hover:underline">página de contato</a>, nos termos da nossa <a href="<?= base_url('politica-de-privacidade.php') ?>" class="text-brand-primary hover:underline">Política de privacidade</a>.</p>

    <h2 class="pt-4 text-lg font-bold">13. Alterações destes Termos</h2>
    <p>O Habitou Imóveis, de tempos em tempos, poderá modificar estes Termos de Uso, sem aviso prévio individual — a versão vigente é sempre a publicada nesta página, com a data da última atualização ao final. VOCÊ entende e aceita que deverá revisar estes Termos de Uso periodicamente, e que o uso continuado da plataforma após uma alteração representa a aceitação da nova versão.</p>

    <h2 class="pt-4 text-lg font-bold">14. Legislação Aplicável e Foro</h2>
    <p>Estes Termos de Uso são regidos pelas leis da República Federativa do Brasil, em especial o Código Civil, o Código de Defesa do Consumidor (no que for aplicável à relação entre Usuário e portal) e a Lei Geral de Proteção de Dados. Fica eleito o foro do domicílio do Usuário para dirimir quaisquer controvérsias decorrentes destes Termos, salvo disposição legal em contrário.</p>

    <p class="pt-6 text-xs text-brand-text-secondary">Estes Termos de Uso devem ser lidos em conjunto com a nossa <a href="<?= base_url('politica-de-privacidade.php') ?>" class="text-brand-primary hover:underline">Política de privacidade</a> e, para Anunciantes assinantes de um plano pago, com os <a href="<?= base_url('termos-assinatura.php') ?>" class="text-brand-primary hover:underline">Termos do contrato de assinatura</a>. Ainda com dúvidas? Confira a nossa <a href="<?= base_url('guias.php') ?>" class="text-brand-primary hover:underline">Central de ajuda</a> ou fale conosco pela <a href="<?= base_url('fale-conosco.php') ?>" class="text-brand-primary hover:underline">página de contato</a>.</p>
  </div>
</div>
<?php require __DIR__ . '/includes/footer.php'; ?>
